### ISSUE TITLE
chrome多图上传，点击选择图片后打开文件界面反应慢（大概需要1-2s）

### ISSUE THREAD

**Issue by tystudy** [bailangzhan/yii2-webuploader#1]
1.chrome多图上传，点击选择图片后，大概需要1-2s，才能弹出打开文件界面？
建议在参数设置中
 //'mimeTypes' => 'image/*',               //打开速度慢
  'mimeTypes' =>'image/gif,image/jpg,image/jpeg,image/bmp,image/png'    //打开速度没有延迟

2.上传图片点击旋转之后，实际图片并没有旋转？

这是我用过最好的yii图片上传，希望后续可以增加图片的拉伸，压缩，剪裁等实用功能，cool！！

**Comment by bailangzhan** [comment]
@tystudy  增加了压缩，裁剪功能。
